---
title: Marcus Tan's Portfolio
timezone: Asia/Kuala_Lumpur
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-minimal
name: Marcus Tan's Portfolio
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"
